import type { Property } from "./types";

export const SEED_PROPERTIES: Property[] = [
  {
    id: "seed-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    name: "Contemporary Villa in Nueva Andalucía",
    slug: "contemporary-villa-nueva-andalucia",
    short_description:
      "A refined contemporary villa set within a private gated community, offering sweeping sea views and resort-style amenities.",
    long_description:
      "Positioned in one of Nueva Andalucía's most prestigious addresses, this meticulously designed villa represents the pinnacle of modern Andalusian living. The open-plan interior flows seamlessly onto expansive terraces, where an infinity pool frames panoramic views of the Mediterranean. Four generous bedroom suites, each with en-suite bathrooms, provide exceptional private comfort. The property features a fully equipped kitchen with bespoke cabinetry, a dedicated home cinema, and a double garage. Situated within a gated community with 24-hour security, the villa sits moments from Puerto Banús and the amenities of Nueva Andalucía.",
    price: 2450000,
    price_label: "€2,450,000",
    location: "Nueva Andalucía",
    address: "Urb. Los Naranjos, Nueva Andalucía, Marbella",
    bedrooms: 4,
    bathrooms: 4,
    internal_area: "520 m²",
    plot_size: "1,200 m²",
    outdoor_space: "Terrace 180 m²",
    property_type: "Villa",
    listing_type: "For Sale",
    status: "Available",
    pets: "Upon request",
    instagram_url: null,
    tiktok_url: null,
    features: ["Pool", "Sea view", "Garage", "Garden", "Gated community"],
    published: true,
    featured: true,
    property_images: [
      {
        id: "img-seed-1",
        property_id: "seed-1",
        url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200",
        storage_path: "",
        alt: "Contemporary Villa in Nueva Andalucía",
        sort_order: 0,
        is_cover: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "seed-2",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    name: "Sea View Penthouse on the Golden Mile",
    slug: "sea-view-penthouse-golden-mile",
    short_description:
      "An exceptional penthouse residence on Marbella's celebrated Golden Mile, with panoramic sea and mountain views.",
    long_description:
      "Occupying the entire top floor of one of the Golden Mile's most celebrated buildings, this penthouse commands uninterrupted views from Gibraltar to the African coast. Three elegantly proportioned bedroom suites are complemented by three bathrooms finished in imported marble. The wraparound terrace — over 120 square metres — functions as an outdoor living room, complete with a private jacuzzi and outdoor kitchen. The interior has been conceived by a noted interior architect, with bespoke joinery, climate control throughout, and a fully equipped chef's kitchen. Direct beach access and a 24-hour concierge service complete the offering.",
    price: 1850000,
    price_label: "€1,850,000",
    location: "Golden Mile",
    address: "Paseo del Mar, Marbella Golden Mile",
    bedrooms: 3,
    bathrooms: 3,
    internal_area: "280 m²",
    plot_size: null,
    outdoor_space: "Terrace 120 m²",
    property_type: "Penthouse",
    listing_type: "For Sale",
    status: "Available",
    pets: "Not allowed",
    instagram_url: null,
    tiktok_url: null,
    features: ["Sea view", "Terrace", "Gym", "Lift", "Private parking"],
    published: true,
    featured: true,
    property_images: [
      {
        id: "img-seed-2",
        property_id: "seed-2",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
        storage_path: "",
        alt: "Sea View Penthouse Golden Mile",
        sort_order: 0,
        is_cover: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "seed-3",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    name: "Minimal Apartment near Puente Romano",
    slug: "minimal-apartment-puente-romano",
    short_description:
      "A precisely renovated apartment steps from Puente Romano, designed for clients who value restraint and location above all.",
    long_description:
      "Situated in one of Marbella's most coveted micro-locations, this refined two-bedroom apartment has been completely redesigned with an emphasis on material quality and spatial clarity. Polished concrete floors, bespoke kitchen cabinetry, and imported stone bathrooms create an atmosphere of calm precision. The property is positioned moments from the celebrated Puente Romano resort, Marbella's finest dining, and the beach promenade. An ideal pied-à-terre or investment property in one of the Costa del Sol's most enduring addresses.",
    price: 695000,
    price_label: "From €695,000",
    location: "Marbella",
    address: "Marbella, near Puente Romano",
    bedrooms: 2,
    bathrooms: 2,
    internal_area: "145 m²",
    plot_size: null,
    outdoor_space: "Terrace 25 m²",
    property_type: "Apartment",
    listing_type: "For Sale",
    status: "Available",
    pets: "Not allowed",
    instagram_url: null,
    tiktok_url: null,
    features: ["New renovation", "Terrace", "Lift", "Private parking"],
    published: true,
    featured: true,
    property_images: [
      {
        id: "img-seed-3",
        property_id: "seed-3",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
        storage_path: "",
        alt: "Minimal Apartment near Puente Romano",
        sort_order: 0,
        is_cover: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
];
